### ISSUE TITLE
KeyError: 'BOT_TOKEN'

### ISSUE THREAD

**Issue by Mailovskii** [noes14155/Telegrambot-with-GPT4free#1]
Hello, help pls)
![image](https://github.com/noes14155/Telegrambot-with-GPT4free/assets/132333972/76b5c396-b14e-43b9-959d-f636b4ad55d5)
![image](https://github.com/noes14155/Telegrambot-with-GPT4free/assets/132333972/b248a696-f2d2-4f73-85e4-402ab3232a0f)
![image](https://github.com/noes14155/Telegrambot-with-GPT4free/assets/132333972/96c9e494-1e8d-442f-a48d-c4194523448b)

**Comment by noes14155** [comment]
add you bot_token and rename example.env to .env

**Comment by noes14155** [comment]
remove your existing installation of gpt4free. Its already included
pip uninstall gpt4free

**Comment by Mailovskii** [comment]
> удалите существующую установку gpt4free. В него уже включен pip uninstall gpt4free

I did as you said. I added the tokens to the example.env file, then renamed the file to ".env".
Next, I deleted gpt4free, after which I get back the error I created this thread with :(
![image](https://github.com/noes14155/Telegrambot-with-GPT4free/assets/132333972/6eae486e-a747-40d9-ae2e-b5ee1f6e1e07)
![image](https://github.com/noes14155/Telegrambot-with-GPT4free/assets/132333972/5d2e62ed-2247-48dd-bff2-c92c9bd8626b)
![image](https://github.com/noes14155/Telegrambot-with-GPT4free/assets/132333972/f59514d2-9c0a-48ae-a0e8-227271ee6d5b)

**Comment by Mailovskii** [comment]
Contacted the author on Telegram, thanks.
If anyone has the same problem, on lines 18 and 19 change to 
BOT_TOKEN = "BOT_TOKEN"
POE_TOKEN = "POE_TOKEN" 
and insert the desired tokens there

**Comment by Suburbanno** [comment]
![image](https://github.com/noes14155/Telegrambot-with-GPT4free/assets/13632826/b037ce7b-8b89-42c9-8fcc-21cccb4ca407)

![image](https://github.com/noes14155/Telegrambot-with-GPT4free/assets/13632826/b8fca328-f7b9-4c0d-a34f-05251fbe5eb3)

@noes14155 help

**Comment by noes14155** [comment]
Check your bot token. Add it in env file

**Comment by Suburbanno** [comment]
> Check your bot token. Add it in env file. Did you rename example.env to .env

its fixed, for some reason vscode saved it as .env.txt

**Comment by Suburbanno** [comment]
> Check your bot token. Add it in env file. Did you rename example.env to .env

![image](https://github.com/noes14155/Telegrambot-with-GPT4free/assets/13632826/0ba4e378-15b4-4726-b98d-fc096cb0d1c7)
btw i have this error in /img command

**Comment by noes14155** [comment]
are you using the latest commit. I thought i already fixed that
