### ISSUE TITLE
A request to the Telegram API was unsuccessful

### ISSUE THREAD

**Issue by vasmarfas** [noes14155/Telegrambot-with-GPT4free#2]
I cloned this repo.
Created venv using:
1) python3 -m venv venv
2) source venv/bin/activate
Installed reqs: pip3 install -r requirements.txt
Launched bot (in venv): python main.py

Got this error:
(venv) www-data@server-home:/media/bad-hdd-nextcloud/nextcloud-data/Programms/Telegrambot-with-GPT4free$ python main.py
/media/bad-hdd-nextcloud/nextcloud-data/Programms/Telegrambot-with-GPT4free/venv/lib/python3.10/site-packages/whisper/timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
2023-06-16 01:00:12,842 (async_telebot.py:431 MainThread) ERROR - TeleBot: "Unhandled exception (full traceback for debug level): A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first"

How to fix it? I need to run this project in venv because in system i got this errors:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
qqddm 0.1.1 requires httpx~=0.23.1, but you have httpx 0.24.1 which is incompatible.
python-telegram-bot 20.2 requires httpx~=0.23.3, but you have httpx 0.24.1 which is incompatible.

**Comment by noes14155** [comment]
Another bot is running probably

**Comment by vasmarfas** [comment]
> Another bot is running probably

I have another aiogam bot running in different process. Does it conflicting with your bot?

**Comment by noes14155** [comment]
Its using the same token or it uses a webhook. so another bot won't work. telegram API won't be able to connect
