### ISSUE TITLE
base URLs failed

### ISSUE THREAD

**Issue by hblink** [noes14155/Telegrambot-with-GPT4free#31]
here is the error message
INFO:aiogram.dispatcher.dispatcher:Start polling.
Error making the request with https://gpt4.gravityengine.cc: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://gpt4.xunika.uk/')
Retrying with a different base URL.
 on the bot it says 
All base URLs failed to provide a response.

**Comment by noes14155** [comment]
You are using old code. Please update the code. I already updated those urls before 2 weeks
