### ISSUE TITLE
persona missing in db

### ISSUE THREAD

**Issue by hblink** [noes14155/Telegrambot-with-GPT4free#32]
....
File "/home/papa/Telegrambot-with-GPT4free/bot/language_manager.py", line 37, in local_messages

lang, persona = self.db_connection.get_settings(user_id)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/papa/Telegrambot-with-GPT4free/bot/database.py", line 46, in get_settings

row = self.conn.execute(query, (user_id,)).fetchone()

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

sqlite3.OperationalError: no such column: persona

this is just my opinion about the error

Based on the error traceback, the issue seems to be caused by the database not having the expected 'persona' column in the settings table.

Looking at database.py, the create_tables() method defines the settings table with only 'user_id' and 'lang' columns. The 'persona' column is missing.

Later in get_settings(), the code tries to query the 'persona' column, which results in the sqlite3.OperationalError since that column does not exist.

**Comment by noes14155** [comment]
Because you are using old code

**Comment by hblink** [comment]
> Because you are using old database file. Use the new code. Download the repository first. Then delete the chatbot.db if exist

you were right, it is working fine, how does one send external files, what command to use

**Comment by noes14155** [comment]
what do you mean by externa files
