### ISSUE TITLE
Select from the models or providers

### ISSUE THREAD

**Issue by hblink** [noes14155/Telegrambot-with-GPT4free#37]
i tried changing the model and ever since thank i keep getting 
Select from the models or providers

i have tried restarting bot, delete the DB, it just keeps recurring. 

i also regenerated the key and here is the usage from chimeraGPT bot
![Screenshot_2023-08-13_10-32-36](https://github.com/noes14155/Telegrambot-with-GPT4free/assets/22095581/0e031b13-bc30-4647-87e8-dc8c2b90a911)

**Comment by noes14155** [comment]
should be ok now
