### ISSUE TITLE
error while running Bot

### ISSUE THREAD

**Issue by hblink** [noes14155/Telegrambot-with-GPT4free#4]
Traceback (most recent call last):
telegrambot_gpt4free  |   File "/usr/local/lib/python3.10/urllib/request.py", line 1348, in do_open
telegrambot_gpt4free  |     h.request(req.get_method(), req.selector, req.data, headers,
telegrambot_gpt4free  |   File "/usr/local/lib/python3.10/http/client.py", line 1283, in request
telegrambot_gpt4free  |     self._send_request(method, url, body, headers, encode_chunked)
telegrambot_gpt4free  |   File "/usr/local/lib/python3.10/http/client.py", line 1329, in _send_request
telegrambot_gpt4free  |     self.endheaders(body, encode_chunked=encode_chunked)
telegrambot_gpt4free  |   File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
telegrambot_gpt4free  |     self._send_output(message_body, encode_chunked=encode_chunked)
telegrambot_gpt4free  |   File "/usr/local/lib/python3.10/http/client.py", line 1038, in _send_output
telegrambot_gpt4free  |     self.send(msg)
telegrambot_gpt4free  |   File "/usr/local/lib/python3.10/http/client.py", line 976, in send
telegrambot_gpt4free  |     self.connect()
telegrambot_gpt4free  |   File "/usr/local/lib/python3.10/http/client.py", line 1448, in connect
telegrambot_gpt4free  |     super().connect()
telegrambot_gpt4free  |   File "/usr/local/lib/python3.10/http/client.py", line 942, in connect
telegrambot_gpt4free  |     self.sock = self._create_connection(
telegrambot_gpt4free  |   File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
telegrambot_gpt4free  |     raise err
telegrambot_gpt4free  |   File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
telegrambot_gpt4free  |     sock.connect(sa)
telegrambot_gpt4free  | OSError: [Errno 99] Cannot assign requested address

I tried asking Google, Bard, Chatgpt no luck, maybe you know?

**Comment by noes14155** [comment]
This means the program cannot bind to the network port. My guess is you don't have privileges if you are using windows try in administrator mode. Or some other program is using that port.

**Comment by hblink** [comment]
the problem it seems is docker, network , it is well beyond me. i am running on a Linux Mint ann Ubuntu variant.

i had to change the docker-compose to build
version: '3.5'
services:
  telegrambot:
    env_file: .env
    container_name: telegrambot_gpt4free
    build:
      context: .
      dockerfile: Dockerfile
      network: host

adding network:build, i guess i need to add in ports?

**Comment by noes14155** [comment]
No need to add ports. I think you are using a docker network. If you don't have any other containers. dockerfile and docker-compose is already in github. or https://pastebin.com/ekW5PanH this is my setup. I don't have a docker network. make appropriate changes for your setup
