### ISSUE TITLE
Transcription of voice messages does not work

### ISSUE THREAD

**Issue by MLNekit** [noes14155/Telegrambot-with-GPT4free#6]
`C:\Users\andre\AppData\Local\Programs\Python\Python311\Lib\site-packages\whisper\transcribe.py:114: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
2023-06-19 18:04:53,222 (async_telebot.py:542 MainThread) ERROR - TeleBot: "[WinError 2] The system cannot find the file specified"`

**Comment by noes14155** [comment]
I couldn't reproduce this issue. Please provide more info so that i can check

**Comment by MLNekit** [comment]
I searched the internet for this problem, a possible problem could be using a different version of python. Which version should I use to make it work correctly?

**Comment by MLNekit** [comment]
What information do I need to provide to determine the problem?

**Comment by noes14155** [comment]
Python 3.10. probably i should put this in the readme

**Comment by MLNekit** [comment]
I run the bot on ubuntu 22.04 without a docker, I removed it completely from the application, but on windows it runs fine, picture recognition works, but no speech

**Comment by noes14155** [comment]
try installling ffmpeg

**Comment by MLNekit** [comment]
I tried it, but unfortunately it did nothing. Maybe I did something wrong when I 
1.translated the bot to my language 
2. removed docker from the application

**Comment by noes14155** [comment]
Please create a pull request if you want to add the lang to this project

**Comment by MLNekit** [comment]
I thought about it. At the day I will try to implement a system for many languages. For example, I may try to create a separate file with phrases in different languages

**Comment by MLNekit** [comment]
It would also be nice to implement a system with access to the bot. so far I have made a dumb comparison by telegram id at the beginning of the request

**Comment by noes14155** [comment]
Yes a seperate file with phrases is a good idea. And i didn't understand your last message

**Comment by MLNekit** [comment]
then I'll show you Xd
`@bot.message_handler(commands=['start', 'hello'])
async def start_handler(call):
    if str(call.chat.id) not in allowed_users:
        await bot.send_message(call.chat.id, "Вы не авторизованы для использования этого бота.")
        return
    db.insert_settings(call.chat.id, 'AI Assist', 'ChatGPT')`
