### ISSUE TITLE
Commands /changeprovider or /changebot doesn't working

### ISSUE THREAD

**Issue by vasmarfas** [noes14155/Telegrambot-with-GPT4free#8]
In fact, everything is said in the name of the issue. When sending these commands, the bot perceives them as plain text and sends them to the services for processing it and generating a response. Judging by the code, there are no command data handlers here, have they been removed or is this a bug?

**Comment by noes14155** [comment]
I have removed it as I removed gpt4free(As gpt4free is not being updated and most of APIs stopped working) Currently only supporting gravityengine.cc

**Comment by noes14155** [comment]
I have removed it as I removed gpt4free(As gpt4free is not being updated and most of APIs stopped working) Currently only supporting gravityengine.cc
